spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

jwt:
  secret: 9d52c1c5835d0525092cb29140711cb14b4e55672411808d37d57b05d5159401

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: auth-service

server:
  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    prometheus:
#      enabled: true
#  metrics:
#    export:
#      prometheus:
#        enable: true
