spring:
  application:
    name: income-expense-service
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    #url: jdbc:postgresql://localhost:5439/postgres
    username: postgres
    password: postgres
    auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 9d52c1c5835d0525092cb29140711cb14b4e55672411808d37d57b05d5159401

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enable: true
